/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "add.h"
#include <sys/types.h>
#include <unistd.h>

int *
add_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static int  result;
	printf("working\n");
	sleep(5);
	printf("finished\n");
	printf("%d\n", getpid());
	result=+argp->a+argp->b;
	/*
	 * insert server code here
	 */

	return &result;
}
